"""Reference data (templates, tax tables, locations) extracted verbatim from
FinancialPlanner_v0_8.py, plus the template-lookup helpers ported from it.

The JSON file is generated by tools/extract_v08_data.py so the numbers stay
identical to v0.8.
"""
from __future__ import annotations

import copy
import json
from functools import lru_cache
from pathlib import Path

DATA_DIR = Path(__file__).parent / "data"


@lru_cache(maxsize=1)
def ref() -> dict:
    with open(DATA_DIR / "reference_data.json", encoding="utf-8") as f:
        return json.load(f)


@lru_cache(maxsize=1)
def default_plan() -> dict:
    with open(DATA_DIR / "default_plan.json", encoding="utf-8") as f:
        return json.load(f)


@lru_cache(maxsize=1)
def demo_plans(raw: bool = False) -> dict:
    """Demo households. demo_plans.json is extracted verbatim from v0.8; demo_overrides.json
    re-tunes them for v2's corrected math (real mortgages, taxes in Monte Carlo) so they show a
    realistic spread of outcomes instead of mostly failing. Pass raw=True for the v0.8 originals."""
    with open(DATA_DIR / "demo_plans.json", encoding="utf-8") as f:
        demos = json.load(f)
    if raw:
        return demos
    ov_path = DATA_DIR / "demo_overrides.json"
    if ov_path.exists():
        with open(ov_path, encoding="utf-8") as f:
            overrides = json.load(f)
        for name, ov in overrides.items():
            if name in demos and not name.startswith('_'):
                demos[name] = apply_demo_override(demos[name], ov)
    return demos


def apply_demo_override(plan: dict, ov: dict) -> dict:
    """Override shape: {set: {key: value}, houses|recurring_expenses|major_purchases|children_list:
    {item name: {field: value} | null (remove)}, add: {list key: [items]}, _note: str}."""
    import copy
    p = copy.deepcopy(plan)
    for k, v in (ov.get('set') or {}).items():
        if isinstance(v, dict) and isinstance(p.get(k), dict):
            p[k] = {**p[k], **v}
        else:
            p[k] = v
    for list_key in ('houses', 'recurring_expenses', 'major_purchases', 'children_list'):
        patch = ov.get(list_key)
        if not patch:
            continue
        items = []
        for it in p.get(list_key) or []:
            name = it.get('name')
            if name in patch:
                if patch[name] is None:
                    continue
                it = {**it, **patch[name]}
            items.append(it)
        p[list_key] = items
    for list_key, extra in (ov.get('add') or {}).items():
        p[list_key] = list(p.get(list_key) or []) + list(extra)
    if ov.get('_note'):
        p['demo_note'] = ov['_note']
    return p


STATISTICAL_STRATEGIES = ["Conservative (statistical)", "Average (statistical)", "High-end (statistical)"]
STATISTICAL_STRATEGIES_LEGACY = ["Conservative", "Average", "High-end"]

HEALTH_CATEGORIES = {"Medical", "Dental", "Vision", "Mental Health", "Healthcare"}

CITY_TO_STATE = {
    'Seattle': 'Washington', 'San Francisco': 'California', 'Los Angeles': 'California',
    'San Diego': 'California', 'Sacramento': 'California', 'Portland': 'Oregon',
    'Austin': 'Texas', 'Houston': 'Texas', 'Dallas': 'Texas', 'New York City': 'New York',
    'NYC': 'New York', 'New York': 'New York', 'Boston': 'Massachusetts', 'Chicago': 'Illinois',
    'Miami': 'Florida', 'Denver': 'Colorado', 'Phoenix': 'Arizona', 'Las Vegas': 'Nevada',
    'Atlanta': 'Georgia', 'Philadelphia': 'Pennsylvania', 'Washington DC': 'District of Columbia',
    'DC': 'District of Columbia',
}


def get_strategy_base_name(name: str) -> str:
    if name.endswith(' (statistical)'):
        return name[:-14]
    if name.endswith(' (custom)'):
        return name[:-9]
    return name


def normalize_strategy_name(name: str) -> str:
    if not name:
        return "Average (statistical)"
    if name.endswith(' (statistical)') or name.endswith(' (custom)'):
        return name
    if name in STATISTICAL_STRATEGIES_LEGACY:
        return STATISTICAL_STRATEGIES[STATISTICAL_STRATEGIES_LEGACY.index(name)]
    if name == "Moderate":
        return "Average (statistical)"
    return f"{name} (custom)"


def _lookup(table: dict, location: str, strategy: str):
    if location in table:
        loc = table[location]
        if strategy in loc:
            return copy.deepcopy(loc[strategy])
        base = get_strategy_base_name(strategy)
        if base in loc:
            return copy.deepcopy(loc[base])
        if f"{base} (statistical)" in loc:
            return copy.deepcopy(loc[f"{base} (statistical)"])
    return None


def adult_template(location: str, strategy: str) -> dict:
    """City -> US state -> Canadian province -> Seattle Average (v0.8 priority)."""
    r = ref()
    strategy = normalize_strategy_name(strategy)
    for table in (r["ADULT_EXPENSE_TEMPLATES"], r["STATE_EXPENSE_TEMPLATES"], r["PROVINCE_EXPENSE_TEMPLATES"]):
        t = _lookup(table, location, strategy)
        if t is not None:
            return t
    state = CITY_TO_STATE.get(location)
    if state:
        t = _lookup(r["STATE_EXPENSE_TEMPLATES"], state, strategy)
        if t is not None:
            return t
    return copy.deepcopy(r["ADULT_EXPENSE_TEMPLATES"]["Seattle"]["Average (statistical)"])


def family_template(location: str, strategy: str, custom: dict | None = None) -> dict | None:
    strategy = normalize_strategy_name(strategy)
    t = _lookup(ref()["FAMILY_EXPENSE_TEMPLATES"], location, strategy)
    if t is None and custom:
        t = _lookup(custom, location, strategy)
    return t


def _age_scale(age: int) -> float:
    if age < 2: return 0.25
    if age < 5: return 0.30
    if age < 12: return 0.40
    if age < 16: return 0.50
    if age < 19: return 0.70
    if age < 23: return 0.50
    if age < 26: return 0.30
    return 0.0


def generate_children_template_from_adult(a: dict, level: str = 'Average') -> dict:
    """Verbatim port of v0.8 generate_children_template_from_adult."""
    g = lambda k: a.get(k, 0)
    s = _age_scale
    t = {}
    t['Groceries'] = [g('Groceries') * s(i) for i in range(31)]
    dining = [0, 0, 0.05, 0.05, 0.10, 0.10, 0.15, 0.15, 0.20, 0.20, 0.25, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50, 0.55,
              0.40, 0.35, 0.30, 0.25, 0.20, 0, 0, 0, 0, 0, 0, 0, 0]
    t['Dining Out'] = [g('Dining Out') * dining[i] for i in range(31)]
    coffee = [0] * 13 + [0.1, 0.15, 0.20, 0.30, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15] + [0] * 9
    t['Coffee Shops'] = [g('Coffee Shops') * coffee[i] for i in range(31)]
    autop = [0] * 16 + [0.5, 0.6, 0.6, 0.5, 0.5, 0.5, 0.4] + [0] * 8
    t['Auto Payment'] = [g('Auto Payment') * autop[i] for i in range(31)]
    gas = [0.05] * 13 + [0.15, 0.20, 0.25, 0.40, 0.50, 0.45, 0.40, 0.35, 0.30, 0.25] + [0] * 8
    t['Gas & Fuel'] = [g('Gas & Fuel') * gas[i] for i in range(31)]
    maint = [0.02] * 13 + [0.10, 0.15, 0.20, 0.35, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15] + [0] * 8
    t['Auto Maintenance'] = [g('Auto Maintenance') * maint[i] for i in range(31)]
    ins = [0] * 16 + [1.2, 1.1, 1.0, 0.8, 0.7, 0.6, 0.5] + [0] * 8
    t['Auto Insurance'] = [g('Auto Insurance') * ins[i] for i in range(31)]
    park = [0] * 16 + [0.3, 0.4, 0.4, 0.3, 0.3, 0.2, 0.2] + [0] * 8
    t['Parking & Tolls'] = [g('Parking & Tolls') * park[i] for i in range(31)]
    transit = [0.05, 0.05, 0.05, 0.05, 0.05, 0.10, 0.10, 0.10, 0.15, 0.15, 0.20, 0.20, 0.25, 0.30, 0.30, 0.20,
               0, 0, 0, 0, 0, 0, 0] + [0] * 8
    t['Public Transit'] = [g('Public Transit') * transit[i] for i in range(31)]
    ride = [0] * 13 + [0.15, 0.20, 0.25, 0.30, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10] + [0] * 8
    t['Ride Shares'] = [g('Ride Shares') * ride[i] for i in range(31)]
    t['Clothing'] = [g('Clothing') * s(i) for i in range(31)]
    t['Personal Care'] = [g('Personal Care') * s(i) for i in range(31)]
    t['Grooming'] = [g('Grooming') * s(i) * (1.2 if 13 <= i < 19 else 1.0) for i in range(31)]
    t['Medical'] = [g('Medical') * s(i) for i in range(31)]
    t['Dental'] = [g('Dental') * s(i) for i in range(31)]
    t['Vision'] = [g('Vision') * s(i) for i in range(31)]
    t['Fitness'] = [g('Fitness') * (0.3 if 13 <= i < 23 else 0) for i in range(31)]
    t['Mental Health'] = [g('Mental Health') * (0.3 if 13 <= i < 23 else 0) for i in range(31)]
    t['Entertainment'] = [g('Entertainment') * s(i) for i in range(31)]
    t['Hobbies'] = [g('Hobbies') * s(i) for i in range(31)]
    t['Subscriptions'] = [g('Subscriptions') * (0.3 if 13 <= i < 23 else 0) for i in range(31)]
    t['Phone'] = [g('Phone') * (0.6 if 13 <= i < 23 else 0) for i in range(31)]
    be = 5000 if level == 'High-end' else 3000 if level == 'Average' else 2000
    t['Baby Equipment'] = [be, be * 0.15, be * 0.10, be * 0.07, be * 0.05] + [0] * 26
    dc = 30000 if level == 'High-end' else 22000 if level == 'Average' else 18000
    t['Daycare'] = [dc] * 5 + [dc * 0.4, dc * 0.3, dc * 0.2, dc * 0.1] + [0] * 22
    sb = 800 if level == 'High-end' else 500 if level == 'Average' else 300
    t['School Supplies'] = [sb * 0.1] * 5 + [sb * i / 13 for i in range(1, 14)] + [0] * 13
    ab = 3000 if level == 'High-end' else 2000 if level == 'Average' else 1200
    act = [0.05, 0.10, 0.15, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
           0.5, 0.4, 0.3, 0.2, 0.15] + [0] * 8
    t['Activities & Sports'] = [ab * act[i] for i in range(31)]
    gb = 1000 if level == 'High-end' else 700 if level == 'Average' else 500
    t['Gifts & Celebrations'] = [gb * (0.5 if i < 18 else 0.7 if i < 30 else 0) for i in range(31)]
    eb = 55000 if level == 'High-end' else 35000 if level == 'Average' else 25000
    t['Education'] = [0] * 18 + [eb] * 4 + [0] * 9
    t['Other Child Expenses'] = [g('Other Personal') * s(i) * 0.5 for i in range(31)]
    return t


@lru_cache(maxsize=256)
def _children_template_cached(location: str, strategy: str) -> str:
    t = _lookup(ref()["CHILDREN_EXPENSE_TEMPLATES"], location, strategy)
    if t is None:
        level = 'Conservative' if 'Conservative' in strategy else 'High-end' if 'High' in strategy else 'Average'
        t = generate_children_template_from_adult(adult_template(location, strategy), level)
    return json.dumps(t)


def children_template(location: str, strategy: str) -> dict:
    """{category: [31 annual amounts for ages 0..30]} in template-base-year dollars."""
    return json.loads(_children_template_cached(location, normalize_strategy_name(strategy)))


# ---- College & private school lookups (from v0.8 get_child_expenses) ----
PRIVATE_SCHOOL = {'Seattle': 20000, 'Sacramento': 18000, 'Houston': 15000, 'New York': 35000,
                  'San Francisco': 32000, 'Los Angeles': 25000, 'Portland': 17000}
PUBLIC_TUITION = {'Seattle': 12000, 'Sacramento': 10000, 'Houston': 11000, 'New York': 13000,
                  'San Francisco': 10000, 'Los Angeles': 10000, 'Portland': 12000}
PRIVATE_TUITION = {'Seattle': 55000, 'Sacramento': 50000, 'Houston': 48000, 'New York': 60000,
                   'San Francisco': 58000, 'Los Angeles': 56000, 'Portland': 52000}
ROOM_BOARD = {'Seattle': 18000, 'Sacramento': 15000, 'Houston': 12000, 'New York': 25000,
              'San Francisco': 24000, 'Los Angeles': 20000, 'Portland': 16000}


def child_expenses_for_age(child: dict, age: int, legacy_table: list | None = None) -> dict:
    """Port of v0.8 get_child_expenses (amounts in today's dollars, not inflated)."""
    if age < 0 or age > 30:
        return {}
    at_college = 18 <= age <= 21
    location = child.get('college_location', 'Seattle') if at_college else child.get('template_state', 'Seattle')
    strategy = child.get('template_strategy', 'Average')
    custom = child.get('custom_expenses')  # v2 addition: per-child override table
    if isinstance(custom, dict) and custom:
        exp = {k: (v[age] if isinstance(v, list) and age < len(v) else 0) for k, v in custom.items()}
    else:
        tmpl = children_template(location or 'Seattle', strategy or 'Average')
        if tmpl and age < len(tmpl.get('Groceries', tmpl.get('Food', []))):
            exp = {k: (v[age] if age < len(v) else 0) for k, v in tmpl.items()}
        elif legacy_table and age < len(legacy_table):
            exp = {k: v for k, v in legacy_table[age].items() if k != 'Age'}
        else:
            exp = {}
    if child.get('school_type', 'Public') == 'Private' and 5 <= age <= 17:
        exp['Education'] = exp.get('Education', 0) + PRIVATE_SCHOOL.get(child.get('template_state', 'Seattle'), 20000)
    if at_college:
        exp['Food'] = exp.get('Food', 0) * 0.3
        exp['Transportation'] = exp.get('Transportation', 0) * 0.4
        exp['Entertainment'] = exp.get('Entertainment', 0) * 0.5
        if child.get('college_type', 'Public') == 'Public':
            tuition = PUBLIC_TUITION.get(location, 12000)
        else:
            tuition = PRIVATE_TUITION.get(location, 55000)
        # v0.8 added tuition on top of the template's own college 'Education'
        # amount (double counting). v2 replaces it: tuition + room & board.
        exp['Education'] = tuition + ROOM_BOARD.get(location, 18000)
    return exp


def location_tax_info(location: str | None):
    """Returns (type, info) like v0.8 get_location_type."""
    r = ref()
    if not location:
        return 'unknown', None
    if location in r["US_STATE_TAX_INFO"]:
        return 'us_state', r["US_STATE_TAX_INFO"][location]
    if location in r["COUNTRY_TAX_INFO"]:
        return 'country', r["COUNTRY_TAX_INFO"][location]
    if location in CITY_TO_STATE:
        st = CITY_TO_STATE[location]
        if st in r["US_STATE_TAX_INFO"]:
            return 'us_state', r["US_STATE_TAX_INFO"][st]
    # Province templates -> treat as Canada if present
    if location in r["PROVINCE_EXPENSE_TEMPLATES"] and "Canada" in r["COUNTRY_TAX_INFO"]:
        return 'country', r["COUNTRY_TAX_INFO"]["Canada"]
    return 'unknown', None


def all_locations() -> list[str]:
    r = ref()
    locs = set(r["ADULT_EXPENSE_TEMPLATES"]) | set(r["STATE_EXPENSE_TEMPLATES"]) | set(r["PROVINCE_EXPENSE_TEMPLATES"])
    return sorted(locs)
