"""Reference data (templates, tax tables, locations) extracted verbatim from
FinancialPlanner_v0_8.py, plus the template-lookup helpers ported from it.

The JSON file is generated by tools/extract_v08_data.py so the numbers stay
identical to v0.8.
"""
from __future__ import annotations

import copy
import json
import os
from functools import lru_cache
from pathlib import Path

DATA_DIR = Path(__file__).parent / "data"


@lru_cache(maxsize=1)
def ref_raw() -> dict:
    """The v0.8 reference data exactly as extracted."""
    with open(DATA_DIR / "reference_data.json", encoding="utf-8") as f:
        return json.load(f)


@lru_cache(maxsize=1)
def corrections() -> dict:
    path = DATA_DIR / "reference_corrections.json"
    if not path.exists() or os.environ.get('FP_RAW_REFERENCE') == '1':
        return {}
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def _r10(x: float) -> float:
    return float(round(x / 10) * 10) if abs(x) >= 100 else float(round(x))


@lru_cache(maxsize=1)
def ref() -> dict:
    """Reference data with the cost-of-living corrections applied (docs/COST_OF_LIVING_AUDIT.md)."""
    r = copy.deepcopy(ref_raw())
    c = corrections()
    if not c:
        return r
    for table, scales in (c.get('location_scale') or {}).items():
        for loc, k in scales.items():
            for strat, cats in (r.get(table, {}).get(loc) or {}).items():
                for cat in cats:
                    cats[cat] = _r10(cats[cat] * k)
    for table, locs in (c.get('strategy_scale') or {}).items():
        for loc, per in locs.items():
            for strat, k in per.items():
                cats = (r.get(table, {}).get(loc) or {}).get(strat)
                if isinstance(cats, dict) and isinstance(k, (int, float)):
                    for cat in cats:
                        cats[cat] = _r10(cats[cat] * k)
    u = c.get('state_uniform_scale') or 1.0
    for st, strats in r.get('STATE_EXPENSE_TEMPLATES', {}).items():
        for strat, cats in strats.items():
            for cat in cats:
                if cat != 'Medical':
                    cats[cat] = _r10(cats[cat] * u)
            med = (c.get('state_medical') or {}).get(st, {}).get(strat)
            if med is not None and 'Medical' in cats:
                cats['Medical'] = float(med)
    # aliases: a location with no template of its own uses another's
    for alias, target in (c.get('aliases') or {}).items():
        for table in ('ADULT_EXPENSE_TEMPLATES', 'CHILDREN_EXPENSE_TEMPLATES', 'FAMILY_EXPENSE_TEMPLATES'):
            if target in r.get(table, {}) and alias not in r[table]:
                r[table][alias] = copy.deepcopy(r[table][target])
    # explicit children templates: daycare correction
    for loc, k in ((c.get('children') or {}).get('explicit_daycare_scale') or {}).items():
        for strat, cats in (r['CHILDREN_EXPENSE_TEMPLATES'].get(loc) or {}).items():
            if 'Daycare' in cats:
                cats['Daycare'] = [_r10(v * k) for v in cats['Daycare']]
    return r


@lru_cache(maxsize=1)
def default_plan() -> dict:
    with open(DATA_DIR / "default_plan.json", encoding="utf-8") as f:
        return json.load(f)


@lru_cache(maxsize=1)
def demo_plans(raw: bool = False) -> dict:
    """Demo households. demo_plans.json is extracted verbatim from v0.8; demo_overrides.json
    re-tunes them for v2's corrected math (real mortgages, taxes in Monte Carlo) so they show a
    realistic spread of outcomes instead of mostly failing. Pass raw=True for the v0.8 originals."""
    with open(DATA_DIR / "demo_plans.json", encoding="utf-8") as f:
        demos = json.load(f)
    if raw:
        return demos
    ov_path = DATA_DIR / "demo_overrides.json"
    if ov_path.exists():
        with open(ov_path, encoding="utf-8") as f:
            overrides = json.load(f)
        for name, ov in overrides.items():
            if name in demos and not name.startswith('_'):
                demos[name] = apply_demo_override(demos[name], ov)
    return demos


def apply_demo_override(plan: dict, ov: dict) -> dict:
    """Override shape: {set: {key: value}, houses|recurring_expenses|major_purchases|children_list:
    {item name: {field: value} | null (remove)}, add: {list key: [items]}, _note: str}."""
    import copy
    p = copy.deepcopy(plan)
    for k, v in (ov.get('set') or {}).items():
        if isinstance(v, dict) and isinstance(p.get(k), dict):
            p[k] = {**p[k], **v}
        else:
            p[k] = v
    for list_key in ('houses', 'recurring_expenses', 'major_purchases', 'children_list'):
        patch = ov.get(list_key)
        if not patch:
            continue
        items = []
        for it in p.get(list_key) or []:
            name = it.get('name')
            if name in patch:
                if patch[name] is None:
                    continue
                it = {**it, **patch[name]}
            items.append(it)
        p[list_key] = items
    for list_key, extra in (ov.get('add') or {}).items():
        p[list_key] = list(p.get(list_key) or []) + list(extra)
    if ov.get('_note'):
        p['demo_note'] = ov['_note']
    return p


STATISTICAL_STRATEGIES = ["Conservative (statistical)", "Average (statistical)", "High-end (statistical)"]
STATISTICAL_STRATEGIES_LEGACY = ["Conservative", "Average", "High-end"]

HEALTH_CATEGORIES = {"Medical", "Dental", "Vision", "Mental Health", "Healthcare"}

CITY_TO_STATE = {
    'Seattle': 'Washington', 'San Francisco': 'California', 'Los Angeles': 'California',
    'San Diego': 'California', 'Sacramento': 'California', 'Portland': 'Oregon',
    'Austin': 'Texas', 'Houston': 'Texas', 'Dallas': 'Texas', 'New York City': 'New York',
    'NYC': 'New York', 'New York': 'New York', 'Boston': 'Massachusetts', 'Chicago': 'Illinois',
    'Miami': 'Florida', 'Denver': 'Colorado', 'Phoenix': 'Arizona', 'Las Vegas': 'Nevada',
    'Atlanta': 'Georgia', 'Philadelphia': 'Pennsylvania', 'Washington DC': 'District of Columbia',
    'DC': 'District of Columbia',
}


def get_strategy_base_name(name: str) -> str:
    if name.endswith(' (statistical)'):
        return name[:-14]
    if name.endswith(' (custom)'):
        return name[:-9]
    return name


def normalize_strategy_name(name: str) -> str:
    if not name:
        return "Average (statistical)"
    if name.endswith(' (statistical)') or name.endswith(' (custom)'):
        return name
    if name in STATISTICAL_STRATEGIES_LEGACY:
        return STATISTICAL_STRATEGIES[STATISTICAL_STRATEGIES_LEGACY.index(name)]
    if name == "Moderate":
        return "Average (statistical)"
    return f"{name} (custom)"


def _lookup(table: dict, location: str, strategy: str):
    if location in table:
        loc = table[location]
        if strategy in loc:
            return copy.deepcopy(loc[strategy])
        base = get_strategy_base_name(strategy)
        if base in loc:
            return copy.deepcopy(loc[base])
        if f"{base} (statistical)" in loc:
            return copy.deepcopy(loc[f"{base} (statistical)"])
    return None


def adult_template(location: str, strategy: str) -> dict:
    """City -> US state -> Canadian province -> Seattle Average (v0.8 priority)."""
    r = ref()
    strategy = normalize_strategy_name(strategy)
    for table in (r["ADULT_EXPENSE_TEMPLATES"], r["STATE_EXPENSE_TEMPLATES"], r["PROVINCE_EXPENSE_TEMPLATES"]):
        t = _lookup(table, location, strategy)
        if t is not None:
            return t
    state = CITY_TO_STATE.get(location)
    if state:
        t = _lookup(r["STATE_EXPENSE_TEMPLATES"], state, strategy)
        if t is not None:
            return t
    return copy.deepcopy(r["ADULT_EXPENSE_TEMPLATES"]["Seattle"]["Average (statistical)"])


def adult_template_exact(location: str, strategy: str, custom: dict | None = None) -> dict | None:
    """Like adult_template but returns None instead of falling back to Seattle.
    `custom` = plan['custom_expense_templates'] ({location: {strategy: {cat: amt}}})."""
    r = ref()
    strategy = normalize_strategy_name(strategy)
    if custom:
        loc = custom.get(location)
        if isinstance(loc, dict):
            for key in (strategy, get_strategy_base_name(strategy), f"{get_strategy_base_name(strategy)} (custom)"):
                if isinstance(loc.get(key), dict) and loc[key]:
                    return copy.deepcopy(loc[key])
    for table in (r["ADULT_EXPENSE_TEMPLATES"], r["STATE_EXPENSE_TEMPLATES"], r["PROVINCE_EXPENSE_TEMPLATES"]):
        t = _lookup(table, location, strategy)
        if t is not None:
            return t
    state = CITY_TO_STATE.get(location)
    if state:
        return _lookup(r["STATE_EXPENSE_TEMPLATES"], state, strategy)
    return None


def adult_template_calibrated(location: str, strategy: str) -> dict | None:
    """Per-adult template calibrated to BLS CEX 2024 levels and BEA 2024 price parities
    (see calibrate.py / docs/COST_DATA_AUDIT.md). None if the location is unknown."""
    from .calibrate import calibrated_adult
    level = get_strategy_base_name(normalize_strategy_name(strategy))
    level = level if level in ('Conservative', 'Average', 'High-end') else 'Average'
    return calibrated_adult(location, level, lambda loc, lv: adult_template_exact(loc, lv))


def adult_template_for(location: str, strategy: str, source: str = 'calibrated', custom: dict | None = None) -> dict:
    """Template a user applies from the UI. source: 'calibrated' (default) | 'v08' (original v0.8 numbers)."""
    if custom:
        t = adult_template_exact(location, strategy, custom) if (location in custom) else None
        if t:
            return t
    if source == 'calibrated':
        t = adult_template_calibrated(location, strategy)
        if t:
            return t
        from .calibrate import national_adult
        level = get_strategy_base_name(normalize_strategy_name(strategy))
        return {k: round(v / 10) * 10 for k, v in national_adult(level if level in ('Conservative', 'Average', 'High-end') else 'Average').items()}
    return adult_template(location, strategy)


def spending_curve(location: str) -> dict:
    """Slider anchors (per adult per year) for a location; see calibrate.spending_curve."""
    from .calibrate import spending_curve as _sc
    return _sc(location, lambda loc, lv: adult_template_exact(loc, lv))


def spending_at_level(location: str, x: float) -> dict:
    from .calibrate import level_at
    return {k: round(v / 10) * 10 for k, v in level_at(spending_curve(location), x).items()}


def cost_of_living(location: str, strategy: str, custom: dict | None = None) -> float | None:
    """Annual per-adult spending for a location + spending level (2024 $), or None if the location is unknown.
    Uses the calibrated data (BEA price parities) so moves scale spending realistically; user-defined
    custom templates win when present."""
    if custom and location in custom:
        t = adult_template_exact(location, strategy, custom)
        if t:
            return float(sum(v for v in t.values() if isinstance(v, (int, float))))
    t = adult_template_calibrated(location, strategy)
    return float(sum(t.values())) if t else None


def col_factor(base_loc: str, base_strat: str, loc: str, strat: str, custom: dict | None = None) -> float:
    """Spending multiplier when moving from (base_loc, base_strat) to (loc, strat).
    Unknown locations keep the base location's costs; a spending-level change still applies."""
    b = cost_of_living(base_loc, base_strat, custom)
    n = cost_of_living(loc, strat, custom)
    if n is None:                       # unknown destination: only the spending level changes
        n = cost_of_living(base_loc, strat, custom) if b is not None else None
    if b is None or n is None or b <= 0:
        return 1.0
    return n / b


def rent_factor(base_loc: str, loc: str) -> float | None:
    """Rent level of `loc` relative to `base_loc` (BEA 2024 RPP rents), None if either is unknown."""
    from .calibrate import rent_factor as _rf
    f = _rf(base_loc, loc)
    if f is not None:
        return f
    idx = corrections().get('rent_index') or {}
    b = idx.get(base_loc) or idx.get(CITY_TO_STATE.get(base_loc, ''))
    n = idx.get(loc) or idx.get(CITY_TO_STATE.get(loc, ''))
    return (n / b) if (b and n) else None


def family_template(location: str, strategy: str, custom: dict | None = None) -> dict | None:
    strategy = normalize_strategy_name(strategy)
    t = _lookup(ref()["FAMILY_EXPENSE_TEMPLATES"], location, strategy)
    if t is None and custom:
        t = _lookup(custom, location, strategy)
    return t


def _age_scale(age: int) -> float:
    if age < 2: return 0.25
    if age < 5: return 0.30
    if age < 12: return 0.40
    if age < 16: return 0.50
    if age < 19: return 0.70
    if age < 23: return 0.50
    if age < 26: return 0.30
    return 0.0


def generate_children_template_from_adult(a: dict, level: str = 'Average', location: str | None = None) -> dict:
    """Verbatim port of v0.8 generate_children_template_from_adult."""
    g = lambda k: a.get(k, 0)
    s = _age_scale
    t = {}
    t['Groceries'] = [g('Groceries') * s(i) for i in range(31)]
    dining = [0, 0, 0.05, 0.05, 0.10, 0.10, 0.15, 0.15, 0.20, 0.20, 0.25, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50, 0.55,
              0.40, 0.35, 0.30, 0.25, 0.20, 0, 0, 0, 0, 0, 0, 0, 0]
    t['Dining Out'] = [g('Dining Out') * dining[i] for i in range(31)]
    coffee = [0] * 13 + [0.1, 0.15, 0.20, 0.30, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15] + [0] * 9
    t['Coffee Shops'] = [g('Coffee Shops') * coffee[i] for i in range(31)]
    autop = [0] * 16 + [0.5, 0.6, 0.6, 0.5, 0.5, 0.5, 0.4] + [0] * 8
    if (corrections().get('children') or {}).get('drop_teen_auto_payment'):
        autop = [0] * 31   # a teen's car is better modelled as a one-time purchase
    t['Auto Payment'] = [g('Auto Payment') * autop[i] for i in range(31)]
    gas = [0.05] * 13 + [0.15, 0.20, 0.25, 0.40, 0.50, 0.45, 0.40, 0.35, 0.30, 0.25] + [0] * 8
    t['Gas & Fuel'] = [g('Gas & Fuel') * gas[i] for i in range(31)]
    maint = [0.02] * 13 + [0.10, 0.15, 0.20, 0.35, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15] + [0] * 8
    t['Auto Maintenance'] = [g('Auto Maintenance') * maint[i] for i in range(31)]
    ins = [0] * 16 + [1.2, 1.1, 1.0, 0.8, 0.7, 0.6, 0.5] + [0] * 8
    t['Auto Insurance'] = [g('Auto Insurance') * ins[i] for i in range(31)]
    park = [0] * 16 + [0.3, 0.4, 0.4, 0.3, 0.3, 0.2, 0.2] + [0] * 8
    t['Parking & Tolls'] = [g('Parking & Tolls') * park[i] for i in range(31)]
    transit = [0.05, 0.05, 0.05, 0.05, 0.05, 0.10, 0.10, 0.10, 0.15, 0.15, 0.20, 0.20, 0.25, 0.30, 0.30, 0.20,
               0, 0, 0, 0, 0, 0, 0] + [0] * 8
    t['Public Transit'] = [g('Public Transit') * transit[i] for i in range(31)]
    ride = [0] * 13 + [0.15, 0.20, 0.25, 0.30, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10] + [0] * 8
    t['Ride Shares'] = [g('Ride Shares') * ride[i] for i in range(31)]
    t['Clothing'] = [g('Clothing') * s(i) for i in range(31)]
    t['Personal Care'] = [g('Personal Care') * s(i) for i in range(31)]
    t['Grooming'] = [g('Grooming') * s(i) * (1.2 if 13 <= i < 19 else 1.0) for i in range(31)]
    t['Medical'] = [g('Medical') * s(i) for i in range(31)]
    t['Dental'] = [g('Dental') * s(i) for i in range(31)]
    t['Vision'] = [g('Vision') * s(i) for i in range(31)]
    t['Fitness'] = [g('Fitness') * (0.3 if 13 <= i < 23 else 0) for i in range(31)]
    t['Mental Health'] = [g('Mental Health') * (0.3 if 13 <= i < 23 else 0) for i in range(31)]
    t['Entertainment'] = [g('Entertainment') * s(i) for i in range(31)]
    t['Hobbies'] = [g('Hobbies') * s(i) for i in range(31)]
    t['Subscriptions'] = [g('Subscriptions') * (0.3 if 13 <= i < 23 else 0) for i in range(31)]
    t['Phone'] = [g('Phone') * (0.6 if 13 <= i < 23 else 0) for i in range(31)]
    be = 5000 if level == 'High-end' else 3000 if level == 'Average' else 2000
    t['Baby Equipment'] = [be, be * 0.15, be * 0.10, be * 0.07, be * 0.05] + [0] * 26
    dc = 30000 if level == 'High-end' else 22000 if level == 'Average' else 18000
    dc_table = ((corrections().get('children') or {}).get('daycare') or {}).get(f'{level} (statistical)') or {}
    if location in dc_table:
        dc = dc_table[location]
    t['Daycare'] = [dc] * 5 + [dc * 0.4, dc * 0.3, dc * 0.2, dc * 0.1] + [0] * 22
    sb = 800 if level == 'High-end' else 500 if level == 'Average' else 300
    t['School Supplies'] = [sb * 0.1] * 5 + [sb * i / 13 for i in range(1, 14)] + [0] * 13
    ab = 3000 if level == 'High-end' else 2000 if level == 'Average' else 1200
    act = [0.05, 0.10, 0.15, 0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
           0.5, 0.4, 0.3, 0.2, 0.15] + [0] * 8
    t['Activities & Sports'] = [ab * act[i] for i in range(31)]
    gb = 1000 if level == 'High-end' else 700 if level == 'Average' else 500
    t['Gifts & Celebrations'] = [gb * (0.5 if i < 18 else 0.7 if i < 30 else 0) for i in range(31)]
    eb = 55000 if level == 'High-end' else 35000 if level == 'Average' else 25000
    t['Education'] = [0] * 18 + [eb] * 4 + [0] * 9
    t['Other Child Expenses'] = [g('Other Personal') * s(i) * 0.5 for i in range(31)]
    return t


@lru_cache(maxsize=256)
def _children_template_cached(location: str, strategy: str) -> str:
    t = _lookup(ref()["CHILDREN_EXPENSE_TEMPLATES"], location, strategy)
    if t is None:
        level = 'Conservative' if 'Conservative' in strategy else 'High-end' if 'High' in strategy else 'Average'
        t = generate_children_template_from_adult(adult_template(location, strategy), level, location)
    return json.dumps(t)


def children_template(location: str, strategy: str) -> dict:
    """{category: [31 annual amounts for ages 0..30]} in template-base-year dollars."""
    return json.loads(_children_template_cached(location, normalize_strategy_name(strategy)))


# ---- College & private school lookups (from v0.8 get_child_expenses) ----
PRIVATE_SCHOOL = {'Seattle': 20000, 'Sacramento': 18000, 'Houston': 15000, 'New York': 35000,
                  'San Francisco': 32000, 'Los Angeles': 25000, 'Portland': 17000}
PUBLIC_TUITION = {'Seattle': 12000, 'Sacramento': 10000, 'Houston': 11000, 'New York': 13000,
                  'San Francisco': 10000, 'Los Angeles': 10000, 'Portland': 12000}
PRIVATE_TUITION = {'Seattle': 55000, 'Sacramento': 50000, 'Houston': 48000, 'New York': 60000,
                   'San Francisco': 58000, 'Los Angeles': 56000, 'Portland': 52000}
ROOM_BOARD = {'Seattle': 18000, 'Sacramento': 15000, 'Houston': 12000, 'New York': 25000,
              'San Francisco': 24000, 'Los Angeles': 20000, 'Portland': 16000}


def child_expenses_for_age(child: dict, age: int, legacy_table: list | None = None) -> dict:
    """Port of v0.8 get_child_expenses (amounts in today's dollars, not inflated)."""
    if age < 0 or age > 30:
        return {}
    at_college = 18 <= age <= 21
    location = child.get('college_location', 'Seattle') if at_college else child.get('template_state', 'Seattle')
    strategy = child.get('template_strategy', 'Average')
    custom = child.get('custom_expenses')  # v2 addition: per-child override table
    if isinstance(custom, dict) and custom:
        exp = {k: (v[age] if isinstance(v, list) and age < len(v) else 0) for k, v in custom.items()}
    else:
        tmpl = children_template(location or 'Seattle', strategy or 'Average')
        if tmpl and age < len(tmpl.get('Groceries', tmpl.get('Food', []))):
            exp = {k: (v[age] if age < len(v) else 0) for k, v in tmpl.items()}
        elif legacy_table and age < len(legacy_table):
            exp = {k: v for k, v in legacy_table[age].items() if k != 'Age'}
        else:
            exp = {}
    ed = corrections().get('education') or {}
    if child.get('school_type', 'Public') == 'Private' and 5 <= age <= 17:
        loc0 = child.get('template_state', 'Seattle')
        fee = PRIVATE_SCHOOL.get(loc0) or (ed.get('private_school') or {}).get(loc0) or ed.get('private_school_fallback', 20000)
        exp['Education'] = exp.get('Education', 0) + fee
    if at_college:
        red = (corrections().get('children') or {}).get('college_reductions') or \
            {'x0.3': ['Food'], 'x0.4': ['Transportation'], 'x0.5': ['Entertainment']}
        for factor, cats in red.items():
            k = float(factor[1:])
            for cat in cats:
                if cat in exp:
                    exp[cat] = exp[cat] * k
        private = child.get('college_type', 'Public') != 'Public'
        if not private:
            tuition = PUBLIC_TUITION.get(location, ed.get('public_tuition_fallback', 12000))
        else:
            tuition = PRIVATE_TUITION.get(location, ed.get('private_tuition_fallback', 55000))
        rb = ROOM_BOARD.get(location, ed.get('room_board_public_fallback', 18000))
        if private and location not in ROOM_BOARD:
            rb += ed.get('room_board_private_extra', 0)
        # v0.8 added tuition on top of the template's own college 'Education'
        # amount (double counting). v2 replaces it: tuition + room & board.
        exp['Education'] = tuition + rb
    return exp


def location_tax_info(location: str | None):
    """Returns (type, info) like v0.8 get_location_type."""
    r = ref()
    if not location:
        return 'unknown', None
    if location in r["US_STATE_TAX_INFO"]:
        return 'us_state', r["US_STATE_TAX_INFO"][location]
    if location in r["COUNTRY_TAX_INFO"]:
        return 'country', r["COUNTRY_TAX_INFO"][location]
    if location in CITY_TO_STATE:
        st = CITY_TO_STATE[location]
        if st in r["US_STATE_TAX_INFO"]:
            return 'us_state', r["US_STATE_TAX_INFO"][st]
    # Province templates -> treat as Canada if present
    if location in r["PROVINCE_EXPENSE_TEMPLATES"] and "Canada" in r["COUNTRY_TAX_INFO"]:
        return 'country', r["COUNTRY_TAX_INFO"]["Canada"]
    return 'unknown', None


def all_locations() -> list[str]:
    r = ref()
    locs = set(r["ADULT_EXPENSE_TEMPLATES"]) | set(r["STATE_EXPENSE_TEMPLATES"]) | set(r["PROVINCE_EXPENSE_TEMPLATES"])
    return sorted(locs)
