/** Per-page help (v0.8 TAB_HELP, updated for v2). */
export const HELP: Record<string, { what: string; tips: string[] }> = {
  '/': { what: 'A bird’s-eye view of your plan: key numbers, the net-worth path, financial-health checks, this year’s cash flow and alerts.',
    tips: ['Start with the alerts: red and yellow items are the things to fix first.', 'Toggle “Today’s dollars” to see future amounts in today’s buying power.',
      'Everything recalculates instantly and saves automatically as you edit any page.'] },
  '/checkins': { what: 'Regular check-ins keep the plan true to life: update balances, see if you’re on track against the plan’s range, and roll the plan forward.',
    tips: ['A quick update takes 30 seconds; a full check-in about 5 minutes.', 'Turn on email reminders or add the calendar event so you don’t forget.'] },
  '/actuals': { what: 'Record what really happened each year (income, spending by category, taxes, net worth) and compare with the plan.',
    tips: ['Leave blank what you don’t track; totals only count what you fill in.', 'Use the Excel workbook to track month by month, then import it.'] },
  '/people': { what: 'Income, age, raises, job changes or career phases, savings, retirement age and Social Security for each person, plus household settings.',
    tips: ['Income, retirement age and savings have the biggest impact on the projection.', 'Career phases model moves like startup → big tech with bonuses and equity.'] },
  '/spending': { what: 'Personal spending for each adult, shared household costs, recurring costs (cars, trips) and one-time purchases.',
    tips: ['Slide the spending level to a lifestyle that feels right, then fine-tune categories.', 'Recurring and one-time items flow into both the projection and Monte Carlo.'] },
  '/kids': { what: 'Children with age-based costs from birth to 30: childcare, school, activities, healthcare and college.',
    tips: ['Public vs private school and the college location change costs dramatically.', 'Export a child’s cost table to CSV, edit it, and import it back to override the template.'] },
  '/homes': { what: 'Your real estate: purchase price, mortgage (estimate from rate or your actual loan), taxes, insurance, maintenance, and a timeline to live in, rent out or sell.',
    tips: ['Property tax and maintenance rates compound with appreciation, so check them.', 'Future purchases pay the down payment and closing costs from savings in that year.'] },
  '/healthcare': { what: 'Health insurance by age, HSA, Medicare (Part B, D, Medigap), long-term care and other health expenses.',
    tips: ['Healthcare is often the largest retirement expense; bridge coverage before 65 matters for early retirees.'] },
  '/locations': { what: 'Where you live over time. Moves change taxes and, if enabled, everyday prices and rent.',
    tips: ['Moving from a high-cost to a low-cost area can change your projection a lot.', 'Add a custom place for a city the app doesn’t know.'] },
  '/ownership': { what: 'Separate vs marital property: what each of you brought into the marriage, inherited or was given, and what you built together, year by year. Labels only; totals never change.',
    tips: ['Enter the part of today\'s balances that is still separate; the helper grows a wedding-day balance forward.', 'A warning appears in years when separate money has to pay shared costs.', 'Set the rules to match your prenup; the defaults follow your state.'] },
  '/assumptions': { what: 'Investment return, inflation, healthcare inflation, Social Security cuts, taxes and Monte Carlo settings. These drive every model.',
    tips: ['A 6–7% return and 3% inflation are common baselines; test lower returns in Scenarios or Stress tests.'] },
  '/projections': { what: 'Year-by-year projection with your exact inputs, the Monte Carlo range, taxes, and a cash-flow explorer with every category.',
    tips: ['Click any year in the cash-flow timeline to see where the money comes from and goes.', 'In Monte Carlo, if the 25th percentile stays positive the plan is fairly robust.'] },
  '/retirement': { what: 'When to retire and when to claim Social Security, and whether retirement income replaces enough of your pay.',
    tips: ['Delaying Social Security from 62 to 70 raises the benefit by about 77%.'] },
  '/stress': { what: 'Tests your plan against rare, severe events — market crash, hyperinflation, a disabled child, unemployment, early death — at the worst possible time.',
    tips: ['Combine tests into a compound scenario to see how bad events stack.', 'The stoplight shows whether the plan survives in weak (10th) to strong (90th) markets.'] },
  '/timeline': { what: 'All life events in one view: jobs, retirements, kids, homes, moves and big purchases.', tips: [] },
  '/scenarios': { what: 'Save what-ifs, compare them side by side, restore old versions, export reports and import/export plan files.',
    tips: ['Quick what-ifs create a changed copy of your plan with one click.'] },
  '/household': { what: 'Household name, invite code, members and how your data is protected.', tips: ['Share the code with your partner so you both edit the same plan.'] },
}
